# This is a basic workflow that is manually triggered

name: Lint

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: devcontainers-ci
      uses: devcontainers/ci@v0.2.1900000118
      with:
        imageName: "xmllint"
        runCmd: "./lint.sh"
